name: Build

on:
  push:
    branches: [ "2-cicd" ]

permissions: write-all

jobs:
  build-for-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Build
        run: go build

      - name: Binaries
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ github.run_number }}"
          title: Binaries assets
          files: |
            ./luckperms-notifier