name: Build

on:
  push:
    branches: [ "2-cicd" ]

permissions: write-all

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Build
        working-directory: ./build
        run: go build

  build-for-release:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Build API for Linux
        working-directory: ./build
        run: GOOS=linux GOARCH=amd64 go build -o luckperms-notifier

      - name: Binaries
        uses: IdanKoblik/action-automatic-releases@v0.2
        with:
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ github.run_number }}"
          title: Binaries assets
          files: |
            ./build/luckperms-notifier